org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true
# ??????????? 5 ??
org.gradle.internal.lambda.mock.origin.system=0
org.gradle.internal.http.socketTimeout=600000
org.gradle.internal.http.connectionTimeout=600000
systemProp.https.protocols=TLSv1.2,TLSv1.1,SSLv3
systemProp.http.ssl.protocols=TLSv1.2
systemProp.https.ssl.protocols=TLSv1.2
